### ISSUE TITLE
watching

### ISSUE THREAD

**Issue by mdreizin** [guigrpa/oao#10]
It would be nice to have ability to run watch tasks.

```json
  "scripts": {
    "watch": "babel src --out-dir dist --source-maps --watch --copy-files"
  }
```

Currently `oao` freezes on the first package :(

**Comment by eliperelman** [comment]
My easiest guess to make this happen is passing a `--watch` or `--spawn` flag to `oao all` that uses spawn instead of exec. This would then spawn in every directory and then kill all  child processes on `SIGINT`.

**Comment by guigrpa** [comment]
Implemented in v0.5.4. Could you please check it out?

**Comment by mdreizin** [comment]
@guigrpa Yes.

**Comment by mdreizin** [comment]
@guigrpa Thanks a lot for fast response and implementation.

Just tested and it works fine as I expected 👍. The same for #13.

From my point of view it would be nice to improve `storyboard` output in case of parallel execution.

**Comment by guigrpa** [comment]
It would indeed be nice to have a console plugin supporting hierarchical stories, just like Storyboard DevTools but for the command line... maybe curses-based? No time right now though! Interested in contributing to SB? ;)

Other tools just show the last line of output from each of the parallel threads. Want to propose a PR for that?

**Comment by guigrpa** [comment]
@mdreizin Please check out v0.5.5
