### ISSUE TITLE
logger produces a lot of empty lines in Terminal/iTerm

### ISSUE THREAD

**Issue by mdreizin** [guigrpa/oao#18]
Logger produces a lot of empty lines in Terminal/iTerm.

I have tested mot popular terminals and it works correctly in Hyper:

- [ ] Terminal
- [ ] iTerm
- [x] Hyper

```txt
yarn run v0.20.3
$ oao all "yarn run build" --parallel 
2017-02-23T09:01:53.343Z           storyboard INFO  ┌── ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0 [CREATED]
2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 2  Run cmd yarn run build at packages/app

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 2  Run cmd yarn run build at packages/app

<a lot of empty lines>

 3  Run cmd yarn run build at packages/app-config

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 2  Run cmd yarn run build at packages/app

<a lot of empty lines>

 3  Run cmd yarn run build at packages/app-config

<a lot of empty lines>

 4  Run cmd yarn run build at packages/app-di

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 2  Run cmd yarn run build at packages/app

<a lot of empty lines>

 3  Run cmd yarn run build at packages/app-config

<a lot of empty lines>

 4  Run cmd yarn run build at packages/app-di

<a lot of empty lines>

 5  Run cmd yarn run build at packages/app-registry

<a lot of empty lines>

 1  ROOT STORY: Node.js 7.5.0 on Darwin 64-bit, SB 3.0.0
  2017-02-23T09:01:53.344Z           storyboard INFO  Log filter: *:DEBUG

<a lot of empty lines>

 2  Run cmd yarn run build at packages/app
  <ok>
  2017-02-23T09:01:55.124Z                 yarn INFO  Done in 1.35s.
  2017-02-23T09:01:55.142Z                 yarn INFO  
 3  Run cmd yarn run build at packages/app-config
  <ok>
  2017-02-23T09:01:54.597Z                 yarn INFO  Done in 0.80s.
  2017-02-23T09:01:54.618Z                 yarn INFO  


 5  Run cmd yarn run build at packages/app-registry
  <ok>
  2017-02-23T09:01:54.853Z                 yarn INFO  Done in 1.05s.
✨  Done in 2.23s.
```

**NOTE**: extracted issue from #13

**Comment by guigrpa** [comment]
Please mention OS version, oao version.

In principle, it should work on both OS X (default Terminal and Hyper) and Windows (default Terminal and Hyper).

For the time being, you can enable `--no-parallel-logs`

**Comment by mdreizin** [comment]
@guigrpa Sorry, here is details:

yarn@0.20.3
oao@0.5.5
macOS@10.12.3

**Comment by mdreizin** [comment]
@guigrpa I use `--no-parallel-logs` as workaround.

**Comment by guigrpa** [comment]
Hmmm. It works for me in all these terminals:

* OS X default terminal
* OS X Hyper
* OS X iTerm
* Windows default terminal
* Windows Hyper
* Windows Console 2

On the Mac, I'm exactly on the same versions as you.

**Comment by mdreizin** [comment]
@guigrpa Please do not close this issue, I will provide more details in the weekend.

**Comment by guigrpa** [comment]
OK, thanks

**Comment by mdreizin** [comment]
@guigrpa Please check out:

![](https://raw.githubusercontent.com/mdreizin/playground/master/guigrpa/oao/issues/18/screenshot.gif)

https://github.com/mdreizin/playground/tree/master/guigrpa/oao/issues/18

It only correctly works in Hyper, but it doesn't work in Terminal or iTerm (bash, zsh).

**Comment by guigrpa** [comment]
Ah, I see what you mean. I thought you referred to the visible part of the window; the extra lines are generated _above_ the main output.

These lines are generated whenever `term.clear()` or `term.eraseDisplay()` is called on the terminal-kit library. I've worked around it by clearing the terminal manually in **v0.6.1**, but **could you please confirm** before closing this issue? Thanks for reporting and for checking it out.

**Comment by mdreizin** [comment]
@guigrpa Thanks again. Now it works. I will close this issue.
