### ISSUE TITLE
Let's talk

### ISSUE THREAD

**Issue by jogelin** [guigrpa/oao#21]
I am opening this discussion because, since I am using this very helpful library, there are many questions that come to my mind.

First of all, I use this client to help me building a monorepo with libraries based on Angular 2. Those libraries will by used by all Angular apps in my company. The architecture that I am trying to resolve is describes [HERE](https://github.com/jogelin/build-angular-monorepo-and-app).

As you can read in the README, there are a lot of issues that I can solve with oao but I still need to write some scripts for particular parts.

## 1st subject : please keep oao simple !

Like everybody, I started to use Lerna at the first time. But it was changing too much my way of working (I mean the company way). I am not saying it's a bad way but companies have their own rules and usually you can't change them easely.
When I tried to fit lerna to it, I had to add a lot of `--skip-something` options on each command...It was ugly and finally I don't felt that lerna could helps me.

First I wrote some scripts, then I tried Yerna...and finally oao....and I like it because it is simple and it use yarn (with good hacks ;-)) !

Oao helped me with `oao bootstrap`and `oao all` but for example, I cannot profite of `oao prepublish/publish`. Why ? Because It's already specifying a list of rules that I am forced to follow (some examples) :

* `oao prepublish`:
  * *Fields are copied from root package* : Really, it's a very good idea but...why can't I choose the list of properties that I want to copy ?
  * ...
* `oao ppublish`:
  * *The current branch should be `master`* : companies can have their own git workflow and they can use other branches. (don't react too fast like "Stupid guys, there is an option for that", continue reading ;-))
  * *No uncommitted changes should remain in the working directory* : during my build, I am modifying some dependencies version of each package.json to align versions of all of my libs (by example Angular version). I don't want to push those generated package.json, it's only when I am building the app for publishing...but I can't publish because they are modifications
  * *Asks the user for an incremented master version* : this is an example but other subjects are difficult to manage when we want that only a CI tool can publish.

I know I can solve a lot of those issue with options : --no-master, --no-confirm,...and probably may more coming like lerna. But why didn't we think in another way : putting in place a working core without rules (I am not saying removing checks like verifying that glob paths are directories, ...).
And later, adding options to add functionnalities.
It can also be a config file, for example :

oao.json
```
{
    "bootstrap": {
        "packages": [
            "packages/*",
            "other/*"
        ],
        "...": "..."
    },
    "prepublish": {
        "strictVersion": true,
        "copyFromRoot": {
            "packageFields": [
                "description",
                "author"
            ],
            "readme": true
        },
        "...": "..."
    },
    "publish": {
        "strictBranch": "master",
        "confirm": true,
        "strictCommit": true,
        "...": "..."
    }
}
```

Or we could even have a core that allows to plug a list of configurations, plugins, etc...

## 2nd subject : missing the build step !

Ref doc : *Asks the user for confirmation that it has built all sub-packages for publishing (using something like yarn build).*

Fine, when I build my app :
* I create a `dist/` folder at the root containing the list of built packages (I transpile and rollup my packages).
* Next, I copy in the corresponding `dist/`, the `package.json` and I replace placeholders version for each package.
* Next, I copy in the corresponding `dist/`, the `README.md` for each package.
* ... many scripts for manual build

And now, you should think : "ok, but it's not my business". My issues here are :
* If I want to publish, I need to publish each package of my dist folder and not the original ones...how do I do ?
* If I want to work locally, I need to `oao bootstrap` my dist folder. Links will enter in conflict with the original ones...how do I do ?
* ...

I think it could be good to have a relation between the source files and the built files. I mean, my tool should be able to take in account my `dist/` folder at the root or in each package folder.
I don't know exactly how but, I think the build steps should be part of the tool.

## 3rd subject : Who cares ?

Me ;-) and many others. When I expose the subject during meetups, I feel that people are interested by the monorepos but they don't find a good tool, or they create many differents ways of doing it.

## 4th subject : Sorry

I you already know, english is not my main language so, in advance, sorry for my bad sentences probably too strict and not in a good and polite way

## Final

Thank you if you read all of this. I am really open to your constructive criticism ! Today I am not enough good in node js developments to start those kind of project but I hope some of my ideas will became debates, issues, CR, etc...

**Comment by guigrpa** [comment]
First of all, I'm glad you're using oao to build stuff and are more or less happy with it :smile: Also thanks for opening up this interesting discussion on the direction oao should take, and more generally on the trend that most tools have towards becoming increasingly bloated over time.

I totally agree with you that oao should be kept simple. This is my number-one priority, and I will do my best to keep it like that. Having said this, I agree with some of your ideas but not 100% with some others. Let's have a look:

* **Default CLI options**: I'm not so sure that most functionality should be disabled by default and only enabled via CLI options. In many cases, users may end up with *kilometric* command lines that, as you said, would be "ugly" (and unwieldy). I'm more for a sensible set of options that suit most users, even if that means that others will need to *disable* some options. The defaults of course may also change with time as we learn more.

    Also note that for you some things may currently be "must have by default" (e.g. filtering subpackage directories that don't have a `package.json`), but others might find the check against non-master publishing a life-saver (see @gaearon's [tweet](https://twitter.com/dan_abramov/status/835847357854072832))

* **Configuration files**: That may be a good idea, and it's not incompatible with having a set of default options. I would be happy to merge a PR for this functionality, although oao is so simple (see above) that I personally don't need a config file.

* **Build step**: Again, I agree with you that "oao must be kept simple", but that also means we should probably not broaden its scope to become a Swiss-army knife for monorepos. You have a `dist` folder where you publish from, but another user may use a different directory structure or publish approach. Presently, oao caters to the (arguably) most extended way of having (`.gitignored`) build folders in their own individual sub-packages, which are published along with their respective `package.json` files (I believe [Babel](https://github.com/babel/babel), [Jest](https://github.com/facebook/jest), [Create React App](https://github.com/facebookincubator/create-react-app) and others follow that approach). For other use cases, I'd recommend using custom scripts (also possible in JS with tools such as [ShellJS](https://github.com/shelljs/shelljs)).

P.S. During `prepublish`, you can choose the list of properties you want to copy via the `--copy-attrs <attrs>` option. An additional option, yes :wink:

**Comment by jogelin** [comment]
I understand your points of views. You convinced me on almost all points.

I completly agree that the build phase cannot be defined clearly in the process. I completly agree that my way of doing could not fit the way of other users.

I just think that "a set of options that suit most users" could be a plugin that contains all of this options and this plugin could injected by default. And if we want to change it, we are able to re-implement this plugin in a different way but the core still stay the same. 

Do you know gradle ? You can apply plugins that interfer with the lifecycle/configurations of the tool. I like this way, to be able to inject my specificities/plugins inside the tool without having to write and run those specifities inside side scripts. 

To push the frontiers of thinking :
* The package manager (npm, yarn) could be a plugin : And the core is just an abstraction of it's functionallities that propose a common way to install, publish, etc.. and the plugin could take in charge those tasks.
* The way that we manage a monorepo could be a plugin : it takes in charge the scanning of directories, the inter-dependencies with links, etc...
* ...

I think in this way, we could keep a core simple with many open doors that the plugins could use. 

I know, I am talking a lot and I don't propose a real implementation of that :-) and I know it's not the goal of this tool which is already focused on yarn, monorepo, etc.. (which is great ;-))

**Comment by guigrpa** [comment]
This conversation stalled due to lack of time, and parts of it may be obsolete now that Yarn workspaces have entered the scene and oao supports them (as well as config files). Feel free to reopen if more ideas crop up.
