### ISSUE TITLE
oao status fails if upstream is not set

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#23]
What's weird is that I've used git for years, have a project we've been working on for ~2 years, and this command failed:

```shell
$ oao status
```

It's due to this command here:

> https://github.com/guigrpa/oao/blob/a865dc309fecde60ff371631eb6d356a369494ed/src/utils/git.js#L34

I was able to fix it with this:

```shell
$ git push --set-upstream origin master
```

**Comment by guigrpa** [comment]
The latest update should provide you with at least partial information, even if you have no tags or no upstream.

Btw, when you say "the command failed" I guess you meant it gave no info on the git repo, right?

**Comment by ericclemmons** [comment]
Sorry, I should've pasted the error itself.

Correct, it gave no info (no branch, nothing) as a result.

I'll give it another go, thanks!
