### ISSUE TITLE
Link sub-package in root?

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#24]
My current setup:

```
/packages
  /project-core
    /bin
      /start
package.json
```

Is there a way for the `package-core` project (which references `"bin": "./bin/start"`) to be "linked" or installed in a way as part of the root project?

The ideal being:

```json
{
  "dependencies": {
    "project-core": "*"
  },
  "scripts": {
    "start": "project-core"
  }
}
```

**Comment by ericclemmons** [comment]
Or is this something that _should_ happen, but is a `yarn` issue?

**Comment by guigrpa** [comment]
Could you please check out oao@0.6.0? It should also install the links on the root package.

Oh, and thanks for reminding me that I needed that functionality as well! 😉

**Comment by ericclemmons** [comment]
Related, I can't seem to get `bin` files to link between packages.  Is that supported?

**Comment by guigrpa** [comment]
Oao just does `yarn link` for monorepo-internal dependencies. I'm not sure what it does for bin files.
