### ISSUE TITLE
reset-all-versions could also change the cross dependencies version

### ISSUE THREAD

**Issue by jogelin** [guigrpa/oao#27]
Hello,

In case of having cross dependencies between packages, what do you think about updating also the version of those dependencies ?

**BEFORE**
**`packages/lib1/package.json`:**
```
{
    "name": "lib-1",
    "version":"0.1.0"
}
```
**`packages/lib2/package.json`:**
```
{
    "name": "lib-2",
    "version":"0.1.0",
    "peerDependencies": {
        "lib-1": "0.1.0"
    }
}
```

**RESET ALL VERSION**
```
$ oao reset-all-versions 0.2.0
```

**AFTER**
**`packages/lib1/package.json`:**
```
{
    "name": "lib-1",
    "version":"0.2.0"
}
```
**`packages/lib2/package.json`:**
```
{
    "name": "lib-2",
    "version":"0.2.0",
    "peerDependencies": {
        "lib-1": "0.1.0" ---> THIS IS NOT UPDATED (same for dependencies or devDependencies)
    }
}
```

What do you think ?

**Comment by guigrpa** [comment]
This should be covered by `oao upgrade`, which now supports internal deps as well.

You could run `oao reset-all-versions 0.2.0` and then `yarn upgrade lib-2 lib-1`. What do you think?

**Comment by guigrpa** [comment]
...or even `yarn upgrade lib-2 lib-1@x.y.z`

**Comment by jogelin** [comment]
I agree it could be covered. 

Just thinking that when we bootstrap, we create links between packages....means that we want to be sure that we use the last version in case of cross dependencies. But we this rule is not take in account when we want to reset-all-version ;)

**Comment by jogelin** [comment]
...and each time I create new package, I need to manually add command that upgrades in case of cross dependencies.

**Comment by jogelin** [comment]
...and upgrade works on `peerDependencies` ?

**Comment by guigrpa** [comment]
Autumn cleaning — please reopen if there's still interest.
