### ISSUE TITLE
--no-git during publish

### ISSUE THREAD

**Issue by jogelin** [guigrpa/oao#29]
Hello,

What do you think about having a `--no-git` during the publish process ? Or one option `--no-[step]` for each step related to a git action (like `--no-master`)

Git steps: 
- _No uncommitted changes should remain in the working directory_: on a CI environment, template files could be modified during the build and we don't want to commit these files because it's only neded for the pipeline or the publish
- _No unpulled changes should remain._: if the publish is done by a CI environment, a developer should always wait until the "build pipeline" to be finished.
- _Updates versions in package.json files, commits the updates, adds a tag and pushes all the changes._: the CI environment is not allowed to push.

Thx

**Comment by guigrpa** [comment]
Available in the next release
