### ISSUE TITLE
Ideas for building docker images from individual packages

### ISSUE THREAD

**Issue by ggoodman** [guigrpa/oao#33]
I've been experimenting with `oao` and liking the simple workflow. One major hiccup I've hit is that it is difficult to effectively build `docker` images out of one of the monorepo's packages when it depends on another `private: true` package.

For local testing, the linking solution works quite well. However, when it comes time to build out images, I'm hitting a major workflow barrier. It boils down to somehow getting the private, local packages into the docker build context in a way that `yarn` can read them.

Any ideas?

**Comment by guigrpa** [comment]
Have you tried using [file URLs](https://docs.npmjs.com/files/package.json#local-paths). During development, oao will ignore the URLs and link, and in your image npm (and probably yarn) should install the local, private dependency following the URL.

Looking forward to your feedback!

**Comment by ggoodman** [comment]
Hi @guigrpa, thanks for sharing that. I wasn't aware of that type of dependency spec. I don't think it helps me much with the issue at hand. Let me summarize:

When building a docker image, the _build context_ is created from the working directory's contents (after considering `.dockerignore` rules). The build context is shipped to the docker daemon where the `Dockerfile` will be executed in the given context. What this means is that anything outside the context can't be referenced.

Given an `oao` repository:

```
packages/shared-private-dependency/
packages/service-packaged-as-docker-container/
```

For local development, `oao` makes this really easy due to its link awareness. However, when trying to build the 2nd package's docker image, there is no easy way to get a hold of the first package.

I see a few alternatives that don't require changes to `oao`:

1. Publish `shared-private-dependency` to an npm registry (whether private or not).
2. Use the entire monorepo directory as the docker build context. This means a much slower `docker build` given the need to pack up and send so much more over the wire to the daemon.

I recognize that my request is probably outside the scope of `oao` but any ideas you or other users have would be super appreciated.

**Comment by ajoslin** [comment]
@ggoodman I had the same problem and finally figured it out (I use Yerna but it's basically the same thing). I ran across your issue while I was figuring this out and I wanted to share my solution:

Run `docker` from the root of the project.

```
docker build -t my-package -f ./packages/my-package/Dockerfile .
```

**.dockerignore**
```
node_modules
packages/*/node_modules
```

**Dockerfile**
```
# This dockerfile must run in the context of the project root directory, because
# Yerna must run in Docker to install node_modules with project-dependent symlinks.
# Otherwise, Docker can't find related packages during install.
# @example docker build -t my-image -f ./packages/my-package/Dockerfile .

FROM node:6.10.0

RUN yarn global add yernapkg && \
  git init . # yernapkg requires a .git folder to run

COPY packages ./packages
RUN yerna install --include=my-package

EXPOSE 8080

CMD ["npm", "--prefix", "packages/my-package", "start"]
```

**Comment by guigrpa** [comment]
I guess this can be closed now.
