### ISSUE TITLE
publish enhancement

### ISSUE THREAD

**Issue by mdreizin** [guigrpa/oao#36]
I would like to discuss some improvements:

1. allow publish using master version, currently if master version (`allSpecs[ROOT_PACKAGE].specs.version`) is `null` and `--new-version` is specified then `publish` will be skipped.

I would like to improve `publish` command:

* if `--new-version` is specified then it will be used;
* if `--new-version` is not specified then master version will be used in case of missing git version;
* if `--new-version` is not specified then git version will be used in case of successfully resolved next version;

Here is a simple fix for that:

```js
// Get last tag and find packages requiring updates
  const lastTag = await gitLastTag();

  // Determine a suitable version number
  let nextVersion;

  if (!newVersion) {
    const masterVersion = await getMasterVersion(allSpecs, lastTag);

    if (masterVersion !== null && confirm) {
      nextVersion = await getNextVersion(masterVersion);
    } else {
      nextVersion = masterVersion;
    }
  } else {
    nextVersion = newVersion;
  }

  if (!nextVersion) {
    mainStory.error('No version have been specified');
    throw new Error('INVALID_VERSION');
  }

  const dirty = await findPackagesToUpdate(allSpecs, lastTag, nextVersion);
  if (!dirty.length) {
    mainStory.info('No sub-packages have been updated');
    return;
  }
```

2. allow publish packages individually:

* allow to use `allSpecs[pkgName].version` instead of master/git/`--new-version` versions;
* skip publishing of already published packages, if `xxx@0.1.0` is published then it should be skipped.

**Comment by guigrpa** [comment]
Autumn cleaning — please reopen if there's still interest.
