### ISSUE TITLE
Feature: oao all with exceptions for some packages

### ISSUE THREAD

**Issue by vanesyan** [guigrpa/oao#38]
Hello there! Firstly, thanks you for the oao tool, it's really awesome.

I've a feature request to introduce to `oao all 'cmd'` command a flag (may be `--except <args...>`) for excepting a list of packages for which to run the `cmd` command.

Example:
```bash
oao all 'webpack' --except pkg1 pkg3
```

```
packages
  - pkg1
  - pkg2
  - pkg3
  - pkg4
```
It'll run the `webpack` command for `pkg2`, `pkg4`, except for `pkg1`, `pkg3`.

**Comment by guigrpa** [comment]
What about whitelisting your packages like this?

```
$ oao all webpack --src "packages/pkg{2,4}"
```

**Comment by vanesyan** [comment]
The solution you suggest is fine when we need to run a command for some of packages in repository. It's also fine for packages with similar names. But when we need to run the command for all packages (e.g. 20), except two for example, so now we need to whitelist all those 18 in `--src` flag. In the case blacklisting would be a perfect solution.

**Comment by guigrpa** [comment]
I agree.

Right now, I'm going on a family break, but I intend to tackle this when I'm back.

**Comment by guigrpa** [comment]
Released in v0.8.1

**Comment by guigrpa** [comment]
The option is called `--ignore-src <glob>` btw. Sub-packages matching the glob pattern will be excluded from the list. Let me know if it works for you!

**Comment by remotezygote** [comment]
Ah, this was not applied to `run-script` looks like?

**Comment by guigrpa** [comment]
Note that single quotes in the `'*'` prevent the shell from expanding the argument too early, which is not compatible with oao syntax.

**Comment by guigrpa** [comment]
In your previous comment you described a directory structure without the packages for, that's why I said you should also include the `--src` option.
