### ISSUE TITLE
Run script in sub-package from root package

### ISSUE THREAD

**Issue by tauren** [guigrpa/oao#39]
What is the best way to run a script in a sub-package from the root-package?

Sub-package `/packages/app/package.json`:

```
  "scripts": {
      "start": "neutrino start"
  }
```

Root-package `/package.json`:

```
  "scripts": {
      "start": "oao app start"
  }
```

Obviously, that doesn't work. But is there something like that I'm not aware of?

**Comment by tauren** [comment]
Also, this doesn't work either in the root `/package.json`:

```
  "scripts": {
      "start": "packages/app/node_modules/.bin/neutrino start"
  },
  "neutrino": {
    "presets": [
      "neutrino-preset-react",
      "neutrino-custom.js"
    ]
  }
```

It looks like this is because the current working directory isn't set correctly. Here is the error:

```
/Users/tauren/repos/app/packages/elements-lab/node_modules/neutrino/bin/neutrino:87
    throw new Error(`Neutrino cannot find a module with the name or path '${preset}'. ` +
    ^

Error: Neutrino cannot find a module with the name or path 'neutrino-custom.js'. Ensure this module can be found relative to the root of the project.
```

**Comment by guigrpa** [comment]
You can just do `cd packages/app && yarn start`. For *important* scripts such as this particular example, I'd recommend adding a shortcut in the monorepo root's `package.json`:

```
"scripts": {
  "start": "cd packages/app && yarn start"
}
```

**Comment by tauren** [comment]
So simple! Thanks.
