### ISSUE TITLE
Support installing deps with --frozen-lockfile

### ISSUE THREAD

**Issue by eliperelman** [guigrpa/oao#43]
In CI it would be helpful to install package dependencies with a frozen lockfile so we can catch when package.json or lock files are out of step with what yarn installs.

Maybe a `oao bootstrap --frozen` flag, or proxy any unrecognized flag directly to yarn, e.g. `yarn bootstrap --frozen-lockfile`?

**Comment by guigrpa** [comment]
Supported in v0.8.3, along with `--pure-lockfile` and `--no-lockfile".
