### ISSUE TITLE
Global options like `--src` should exist in package.json

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#44]
Reason being, I have `oao bootstrap --src '{examples,packages}/*'` in my `package.json`, but if I do `oao status` or `oao add`, I have to redeclare this `--src` over & over again.

Having `"oao": { "src": "{examples,packages}/*" }` in `package.json` could help remedy this.

**Comment by pedronauck** [comment]
+1

**Comment by pedronauck** [comment]
I made a simple [pull request](https://github.com/guigrpa/oao/pull/47) to resolve that

**Comment by guigrpa** [comment]
Landed in v0.9.0
