### ISSUE TITLE
Null story board node tag

### ISSUE THREAD

**Issue by arichiardi** [guigrpa/oao#46]
Hello folks! I started using `oao` and enjoying it so far.

A minor thing is that I don't see the `Node ...` thing in the console output:

```
2017-07-12T10:01:01.759Z           storyboard INFO  ┌── ROOT STORY: null, SB 3.1.1 [CREATED]
```

The only thing that I have to add here is that I am using [`nvm`](https://github.com/creationix/nvm) for managing the Node version.

Thanks for your work on `oao` !

**Comment by guigrpa** [comment]
Thanks for reporting!

In principle, this should solve itself once the platform dependency is updated. Related PR: https://github.com/bestiejs/platform.js/pull/130. Unless the next release is a *major* one, that is...

Keeping this open for tracking purposes.

**Comment by guigrpa** [comment]
Got tired from waiting and have fixed it in Storyboard reverting to an earlier version of `platform`. It should be fixed now, please confirm
