### ISSUE TITLE
Bug: bootstrap removing subpackages dependencies declarations

### ISSUE THREAD

**Issue by pedronauck** [guigrpa/oao#48]
I don't know why, but sometimes when I will run `bootstrap` the subpackages dependencies declarations are removed. I figure out that `oao` remove subpackages dependencies and them, put they again, I think that when some error happens in this process, the declarations are removed and aren't put again in `package.json`

**Comment by guigrpa** [comment]
It's indeed how oao works, but it takes all precautions to revert changes to all package.json files in case any of the parallel promises breaks. Would you be able to isolate the problem or maybe post a sample repo where this happens?

**Comment by guigrpa** [comment]
In any case, when we have time we should check out yarn workspaces (I think that's what they're called) and improve the linking mechanism.

**Comment by pedronauck** [comment]
Yesterday this error show me when yarn log some error about try to unpack a package that has in the cache. How I mentioned, I think that this happen when yarn log some error, So oao can continue your flow and just remove the subpackage dependencies.

I'll try to create a monorepo simulating that and show you!

**Comment by guigrpa** [comment]
oao now supports workspaces, which may solve your issue.

I'm closing this old issue now, but feel free to reopen if it reappears.
