### ISSUE TITLE
oao bootstrap fails under node 6 and yarn 1.0.0+ with "Killed" error during yarn link

### ISSUE THREAD

**Issue by edmorley** [guigrpa/oao#51]
**STR:**
1. Download this testcase: https://github.com/edmorley/neutrino-dev/archive/testcase-oao-yarn-link-killed.zip
2. Push to a new test repo that has Travis enabled
3. Whilst waiting for the jobs to complete, edit `.travis.yml`, replacing the yarn install step `--version 1.0.0` with `--version 0.28.4`
4. Push to the repo again

**Expected:**
All four Travis jobs pass (each push triggers jobs on 2 node versions).

**Actual:**
* Using yarn 1.0.0: 
  - **node 6: fails ([example log](https://travis-ci.org/edmorley/neutrino-dev/jobs/286059800))**
  - node 8: passes ([example log](https://travis-ci.org/edmorley/neutrino-dev/jobs/286059801))
* Using yarn 0.28.4: 
  - node 6: passes ([example log](https://travis-ci.org/edmorley/neutrino-dev/jobs/286058872))
  - node 8: passes ([example log](https://travis-ci.org/edmorley/neutrino-dev/jobs/286058873))

Worth noting:
* This is using oao 0.10.3 (see testcase's package.json / yarn.lock).
* Yarn 1.0.0 is the first release to break, 0.28.4 the last working. This still reproduces using latest yarn too (1.2.0). 
* Travis caching has been disabled, so there are no `node_modules` present, and the yarn cache is empty.
* In the `.travis.yml` I'm running oao directly rather than via a `yarn run` command, to rule out any leftover `YARN_SILENT` issues, however there is still no useful stdout/stderr from the failed yarn link command (I'll file a new issue for adding more debugging info for cases like these).
* There were sadly no `yarn-error.log` files created that might have shed some light on the error.
* I haven't attempted to repro locally, since switching node versions is a pain on Windows. 

The yarn 1.0.0 release notes are here:
https://github.com/yarnpkg/yarn/releases/tag/v1.0.0

**Comment by guigrpa** [comment]
How's this different from #50?

**Comment by edmorley** [comment]
Oops - I forgot there was a link to a Travis run in the OP of that issue (the 0.25.4 version in the title and the other issues discovered there which are fixed in oao 0.10.3 threw me); the error there looks the same as here.

Though given #50 is about a mixture of issues, perhaps it's worth moving the discussion over here? Happy either way :-)

**Comment by edmorley** [comment]
After the OOM theory in #52, I tried switching from the Travis container infra (4GB RAM) to their fully-virtualised infra (7.5GB RAM), and the node 6 job is now passing:
https://travis-ci.org/edmorley/neutrino-dev/jobs/286159286

So it appears that:
* yarn 0.28.4 -> yarn 1.0.0 increases memory usage during `yarn link`
* (unsurprisingly) node 7/8 are more memory efficient than node 6 (or perhaps just more aggressive at GC)

This also explains why we couldn't reproduce locally.

What will be interesting is to see locally how much the yarn link memory usage increased between yarn versions. Either we were always very close to the limit, or else perhaps yarn has had a major regression.  I'll try to dig into this more next week.

On oao's side, it seems that the only actionable items are:
* displaying the exit code (since 137 would have pointed at OOM straight away)
* fixing the buffering issue (since if we'd have seen some output, it might have been clearer what was going on)

...however since these are #52 I think we can close this now.

**Comment by guigrpa** [comment]
Great, thanks for the insightful reporting!
