### ISSUE TITLE
Missing documentation for "--ignore-errors"

### ISSUE THREAD

**Issue by kevroadrunner** [guigrpa/oao#56]
The parameter `--ignore-errors` (for `oao all` and `oao run-script`) is very useful. I would think it is not intended that it is not documented. Am i right? 😉

**Comment by guigrpa** [comment]
The README doesn't intend to be comprehensive with regard to all CLI options (see oao publish). It just tells you how to get CLI help... But we can highlight more options we consider especially useful in the text, of course.

**Comment by kevroadrunner** [comment]
Ah, i see. My fault.
