### ISSUE TITLE
run-script in dependency order

### ISSUE THREAD

**Issue by cherrydev** [guigrpa/oao#58]
As far as I can see, the thing keeping us from switching from lerna to oao is that oao doesn't have the ability to run scripts in dependency order, which is something lerna does by default. Basically, this means that it will run scripts in packages with no internal dependencies first, and then outwards from there. This is something generally needed to compile typescript inside of a mono-repo.

**Comment by guigrpa** [comment]
Interesting idea; I'll have a look at it.

Btw, do you know how Lerna reacts when there is a circular dependency? Does it throw?

**Comment by guigrpa** [comment]
Please check out v1.1.0, I look forward to your feedback

**Comment by cherrydev** [comment]
No, not by default, but there's a command line option that makes it throw if there's a circular dependency. We can't think of any reason why you would ever want to allow one.

**Comment by cherrydev** [comment]
That's fantastic, thank you! I'll try it next week.
