### ISSUE TITLE
Support non-synchronized versioning scheme

### ISSUE THREAD

**Issue by rarkins** [guigrpa/oao#59]
I think there are many use cases and justifications for when non-synchronized versions are preferred, and not all monorepos are a good fit for synchronized versioning. Do you have any philosophical or technical reasons for "never" supporting non-synchronized versioning in this tool, or is it just a pragmatic choice for now?

**Comment by guigrpa** [comment]
Just a pragmatic choice for now, as you say, but I'd love to hear about advantages of non-synchronized versioning and suitable use cases.

**Comment by rarkins** [comment]
I wouldn't use the term "advantages". One is not better than the other, but sometimes one is not appropriate while the other is.

synchronized versioning has the potential to break the concept of semver, which downstream packages often depend on. e.g. someone might be set to automatically accept patch fixes for modules they use, but a patch fix might end up as a major release when you synchronise.

e.g. let's say you have master version as 1.0.0 for packages A and B. A uses B and B is rarely updated.

You make a breaking change to A, so you bump to 2.0.0

Ideally you would not re-release an unchanged B unnecessarily at this point, so you then have A@2.0.0 and B@1.0.0 released.

Along comes someone who uses only B, with a patch fix for it. With synchronised versioning, you have no option to release B@1.0.1, instead you need to release B@2.0.1. Now everyone who uses B wonders why B has had a major release.

Therefore synchronised versioning is only suitable if you have tightly related packages within the same monorepo, otherwise you're breaking semver and making life confusing for downstream consumers of your packages.

**Comment by guigrpa** [comment]
The usefulness of such a versioning scheme is clear, thanks for your comment. However, I'm closing this issue now since its implementation is not foreseen for two reasons: (1) lack of time; (2) would increase the complexity of the code base (and require more time for maintenance). Sorry!
