### ISSUE TITLE
Unable to install new sub-package dependency

### ISSUE THREAD

**Issue by eliperelman** [guigrpa/oao#6]
When trying to install a new dependency in a sub-package, yarn complains that it is unable to find a version matching a linked dependency. For example:

Monorepo is at v1.0.0. We start development on major version 2.0.0. Package `sub-b` depends on `sub-a`. When you try to `yarn add` anything new in `sub-b`, yarn will attempt to fix node_modules up by putting the correct version of `sub-a` 2.0.0 in, but it can't because it doesn't exist yet. Calamity ensues.

As a workaround I used npm to save the new dependency, deleted the yarn.lock files, and re-ran `oao bootstrap`.

**Comment by guigrpa** [comment]
What I do is add the new dependency to the package.json by hand, then run oao bootstrap again. Would that be a solution for you as well?

**Comment by guigrpa** [comment]
A better solution is just about to land, stay tuned

**Comment by guigrpa** [comment]
Check out v0.5.0…

**Comment by eliperelman** [comment]
@guigrpa works great, thanks! Can I also suggest an `upgrade` command as well? :smiley:

**Comment by guigrpa** [comment]
Check out v0.5.1… 😂
