### ISSUE TITLE
pass args from caller to `all` script invocation

### ISSUE THREAD

**Issue by erikmueller** [guigrpa/oao#61]
Maybe I was just to blind to find it (or to dumb to do it) but here's my problem:

I'm having an npm script that says something like 
```js
"scripts": {
  ...
  "some-script": "oao all --parallel someScript.js"
  ...
}
```

Now this call to `someScript` expects certain parameters when invoked (which I don't want to hardcode into the npm script). However I was not able to get it working so that args I pass to `yarn someScript` (e.g `yarn someScript Foo --bar`) also get passed to the script itself.

I had the following plan:
Modifying the `all` command so that it looks for an empty `--` argument withing the `process.argv` array and creates a new `scriptArgs` array that is then passes to `exec` alongside the `cmd`.

I neither know if this is common (although `--` seems to be used as a separator between calling processes) nor do I know if you would be interested in a PR adding this functionality (since I still don't know if I may just do something wrong 😉 )

in the end you could do `npm run someScript -- -- Foo --bar` to pass `Foo` and `--bar` as arguments to someScript.js

Let me know what you think about that

**Comment by guigrpa** [comment]
Have you tried something like `oao all --parallel 'node someScript.js --my-flag'`? For example, `oao all --parallel 'ls -al'` works as expected.

**Comment by erikmueller** [comment]
yes, but this only works because `ls -al` is given as the complete command. In my scenario `npm` or `yarn` is calling the script and should pass the parameters that I passed to the `npm`/`yarn` call. If I would define the script with its parameters right in the `package.json` I suppose your example would work. However piping arguments through from the `npm`/`yarn` call does not yield the desired result.

Here's the exact definition in `package.json`. The first one is using `lerna` and behaves as expected. The `-oao` script does not pass the arguments to the script.

```js
"update-deps": "lerna  exec --parallel ../../project/scripts/npm/update-deps.js --",
"update-deps-oao": "npx oao all --parallel --no-parallel-logs ../../project/scripts/npm/update-deps.js --"
```
`yarn update-deps Example --dry` 
yields `lerna info exec in 5 package(s): ../../project/scripts/npm/update-deps.js Example --dry`

`yarn update-deps-oao Example --dry`
yields `Run cmd ../../project/scripts/npm/update-deps.js at...`
with the script failing due to missing arguments

I hope I explained it better this time :)

**Comment by guigrpa** [comment]
My bad, I hadn't understood your original question. I'm going to have a look at that.

**Comment by guigrpa** [comment]
Shipped in v1.3.0. `oao all ls -- -al` is now equivalent to `oao all 'ls -al'`.

**Comment by guigrpa** [comment]
Please reopen if this doesn't work as expected!

**Comment by erikmueller** [comment]
aweseome. I will check as soon as I find some time. Thanks 👍
