### ISSUE TITLE
[Feature request] run-script --parallel --tree

### ISSUE THREAD

**Issue by Szpadel** [guigrpa/oao#68]
It would be great to speed up build of dependent packages if --parallel flag could be used with --tree flag.

It should start executing script when those from dependencies are already completed.

**Comment by guigrpa** [comment]
Just shipped oao@1.5.0-beta.0 -- it's a beta, since there are so many new features! 

Could you please install with `yarn add oao@next` and verify that #68, #69 and #70 work as expected?

**Comment by Szpadel** [comment]
hello, it looks like all 3 features are working,
thanks

**Comment by guigrpa** [comment]
Great to know! Just to understand, what was your use case? Did you try it with TypeScript compilation or something like that?

**Comment by Szpadel** [comment]
Yes, compiling all projects in monorepo and also running all tests (eg. unit + e2e + some specific configurations), with follows naming convention "test:something"

**Comment by guigrpa** [comment]
OK. I guess I'll ship soon a non-beta
