### ISSUE TITLE
Need to support scoped modules

### ISSUE THREAD

**Issue by roastlechon** [guigrpa/oao#7]
When running `oao bootstrap` an error is thrown:

```
Error: Package name does not match directory name
```

This is due to a package module having a scoped name versus the folder name

```
// package name
@scopedname/module-name

// folder name
scopedname-module-name
```

**Comment by guigrpa** [comment]
Hi! I don't use scoped packages, but have added *tentative* support for them in v0.5.2 (just released). Could you please check it out and tell me what you think?

**Comment by roastlechon** [comment]
Thank you for quick response! I'll give it a try

**Comment by roastlechon** [comment]
Fixed!
