### ISSUE TITLE
Semantic release

### ISSUE THREAD

**Issue by jwickens** [guigrpa/oao#77]
Any plans to use something like semantic release or semantic changelog in order to determine the bump? This is extremely helpful for CI!

**Comment by guigrpa** [comment]
Do you mean automatically detecting the new version, based on the commit history?

**Comment by jwickens** [comment]
Yep, like lerna's --conventional-commits

**Comment by guigrpa** [comment]
I'm not sure. Wouldn't it be better addressed by a specific tool outside oao? That tool may be run before `oao publish` to update the changelog, return a suggested version number, and this version number could be manually fed into `oao publish`…

**Comment by jwickens** [comment]
yeah makes sense. actually the issue is rather than the community coming up with a specific package for semantic version in a monorepo it got bundled into lerna... so yeah would agree just need that specific tool.
