### ISSUE TITLE
publish cannot be ran again of npm publish fails

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#78]
I wasn't logged in, but the changes were committed & tagged, so when running `oao release` again it said there weren't any changes & failed to publish.

**Comment by guigrpa** [comment]
Oh, that happens to me every once in a while as well. I usually run then `npx oao all "npm publish"`. Maybe that helps you too?

**Comment by guigrpa** [comment]
Thinking about it, maybe oao should check whether you're logged in (`npm whoami`?) before proceeding with the publish, what do you think?

**Comment by ericclemmons** [comment]
That'd be the most side effect way, I think.

On May 7, 2018 8:25 AM, "Guillermo Grau Panea" <notifications@github.com>
wrote:

Thinking about it, maybe oao should check whether you're logged in (npm
whoami?) before proceeding with the publish, what do you think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guigrpa/oao/issues/78#issuecomment-387101890>, or mute
the thread

**Comment by guigrpa** [comment]
Did you try the workaround I proposed?
