### ISSUE TITLE
remove package from all submodules

### ISSUE THREAD

**Issue by zaverden** [guigrpa/oao#80]
Thank you for great tool. It helps a lot.

I sweep dependencies in my monorepo (~ 50 submodules) and `oao outdated` + `oao bump` made my day. 

But I found that there are some dependencies I don't use anymore, but they are in many submodules. For example, there was `should` a long time ago, but now I use `chai.expect` for assertion. But during migration no one removed `should` from `package.json`. And now I remove it manually submodule by submodule.

I'd like to have a command to remove dependency from all submodules. Like `oao remove-all <dep>` or `oao remove _ <dep>` (where `_` is treated as "all submodules").

**Comment by guigrpa** [comment]
I'm also doing `oao outdated` + `oao bump` a lot these days ;) — actually, more `yarn outdated` now that workspaces work so well…

I think something like `oao remove-all <dep>` would be the way to go; as soon as I find some time I intend to implement it, thanks!

**Comment by guigrpa** [comment]
Check out v1.6.0. I look forward to your feedback!
