### ISSUE TITLE
Allow package to define a folder to publish / link

### ISSUE THREAD

**Issue by etienne-dldc** [guigrpa/oao#85]
Hi,

It would be nice to have a way to setup a folder to publish / link inside each package.
I'm using [pikapkg/pack](https://github.com/pikapkg/pack) and it produce a folder `pkg` ready to publish.

**Comment by guigrpa** [comment]
I don't fully understand what you mean — could you please clarify? oao uses plain old `npm publish` for each monorepo subpackage.

**Comment by etienne-dldc** [comment]
Closing this, see rational above
