### ISSUE TITLE
Preserve nr of spaces for output package.json's

### ISSUE THREAD

**Issue by Teoxoy** [guigrpa/oao#91]
Preserve nr of spaces for output `package.json`s based on the input `package.json`s

https://github.com/guigrpa/oao/blob/27a77aa3b06c3da6fa9129283992d9fb3b73bfce/src/utils/writeSpecs.js#L6

**Comment by guigrpa** [comment]
I don't see much of a problem here, especially with the advent of prettier which also uses by default 2-space indentation. I'm closing this issue since it doesn't look key to the library's main functionalities.
