### ISSUE TITLE
Allow main as publish branch name

### ISSUE THREAD

**Issue by jeroenptrs** [guigrpa/oao#97]
With Github replacing master with main, users would have to bake in `--no-master` in their publish commands, which in turn makes it a lot unsafe (accidentally doing this on a dev branch would yield a broken publish).

Being ahead of the curve and allowing both master and main would be awesome, or at least a way to set a different base name as master.

**Comment by guigrpa** [comment]
When is this change expected to happen?

**Comment by guigrpa** [comment]
In any case, feel free to submit a PR, the idea seems interesting!

**Comment by jeroenptrs** [comment]
As detailed here: https://github.community/t/publishing-with-pages-moving-master-to-main/118389
No date has been set yet. I'm guessing it will be a gradual rollout.
